HM about Bob and Sarah
MatveiNikita/FRONT-END-PROJECTS pull request #12
Opened 2024-04-20 09:09 UTC by MatveiNikita

2024-04-23 15:07 UTC, IvanCeban requested changes

2024-04-23 15:07 UTC, IvanCeban commented on Homework№10/script.js
> +console.log(Sarah.checkIBM());
WOW!
 Nice solution!
 
 But it seems like you're repeating yourself. Creating the same functions twice. Can you optimize it?

2024-04-25 15:41 UTC, MatveiNikita commented on Homework№10/script.js
> +console.log(Sarah.checkIBM());
Do you mean that I can call both methods in one method console.log?

2024-04-25 15:44 UTC, MatveiNikita commented on Homework№10/script.js
> +console.log(Sarah.checkIBM());
Please look at my changes
Thank you for yuor feedback

2024-04-29 12:49 UTC, IvanCebanPVT requested changes

2024-04-29 12:49 UTC, IvanCebanPVT commented on Homework№10/script.js
> +
I mean you're duplicating the method checkIBM for both Bob and Sarah.

You can create a separate function and assign it to checkIBM key of Bob and Sarah. 

This is called DRY - Don't Repeat Yourself.

If the code is duplicated - place it into a variable (or in your case - function)

2024-05-02 10:21 UTC, IvanCeban approved these changes
Now it's great!

2024-05-02 18:24 UTC, merged